# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog, QHBoxLayout
from PyQt5.QtGui import QIcon
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        layout=QHBoxLayout()
        layout.addWidget(self.centralwidget)
        
        

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 911, 581))
        self.tabWidget.setObjectName("tabWidget")

                     
        self.SignalViewer = QtWidgets.QWidget()
        self.SignalViewer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SignalViewer.setObjectName("SignalViewer")


        self.BrowseFile = QtWidgets.QPushButton(self.SignalViewer)
        self.BrowseFile.setGeometry(QtCore.QRect(200, 130, 501, 251))
        self.BrowseFile.setObjectName("BrowseFile")        
        self.tabWidget.addTab(self.SignalViewer, "")


        self.PDFEditor = QtWidgets.QWidget()
        self.PDFEditor.setObjectName("PDFEditor")
        self.tabWidget.addTab(self.PDFEditor, "")
        
        self.setLayout(layout)
        #MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signal Viewer"))
        self.BrowseFile.setText(_translate("MainWindow", "Browse Folder For Signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SignalViewer), _translate("MainWindow", "Signal Viewer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PDFEditor), _translate("MainWindow", "PDF Editor"))
        self.BrowseFile.clicked.connect(self.SelectFile)
        


    def SelectFile(self):
        path = self.open_dialog_box()
        print(path)

        FileName = ""
        i=0
        while path[i] != "." or path[i+1] != "t" or path[i+2] != "x" or path[i+3] != "t":
            if path[i] == '/':
                FileName =""
            else:
                FileName = FileName + path[i]
            i=i+1

        Time, Magnitude = np.loadtxt(path,unpack=True)
        self.CreateGraph(Time, Magnitude, FileName)
    
    def CreateGraph(self, time, magnitude, name):
        # Data for plotting
        fig, graph = plt.subplots()
        graph.plot(time, magnitude)

        graph.set(xlabel='Time', ylabel='Magnitude', title=name)
        graph.grid()

        plt.show()

    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        return path



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
